[battery]
disabled = true
full_symbol = ""
charging_symbol = "󰂄 "
discharging_symbol = " "
unknown_symbol = ""
empty_symbol = ""
[[battery.display]]
threshold = 10
[[battery.display]]
threshold = 40